/**
 * Creating a sidebar enables you to: 
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - By default, Docusaurus uses a sidebar from the docs folder.
 *   You can change this behavior by modifying docusaurus.config.js
 */

 // @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'category',
      label: 'New Modules',
      items: [
        'module1-ros2',
        'module2-digital-twin',
        'module3-ai-robot-brain',
        'module4-vla',
      ],
    },
  ],
};

module.exports = sidebars;
