/**
 * Creating a sidebar enables you to  -
 - create an ordered group of docs
 - render a sidebar for each doc as they are navigated to

By default, Docusaurus generates a sidebar from the docs folder.
You can change this configuration to remove all items, add a copy of them, or select new items.
*/

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder. You can change this configuration to remove all items, add a copy of them, or select new items.
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.', // Generates sidebar items based on the docs folder
  }],
};

module.exports = sidebars;